# Generated by Django 3.1.1 on 2020-09-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20200925_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='save_credentials',
            new_name='share_reports',
        ),
    ]
