# Generated by Django 3.1.1 on 2020-09-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_auto_20200925_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='save_server_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='server_address',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='server_username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
    ]
