# Generated by Django 3.1.1 on 2020-09-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20200925_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_username',
        ),
    ]
