# Generated by Django 3.1.1 on 2020-10-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_remove_server_server_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='organisation',
            new_name='server',
        ),
        migrations.AddField(
            model_name='audit',
            name='tmp_res',
            field=models.CharField(default='dfs', max_length=10000),
            preserve_default=False,
        ),
    ]
