# Generated by Django 3.1.1 on 2020-10-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_auto_20201005_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='audit',
            name='tmp_res',
        ),
    ]
