# Generated by Django 3.1.1 on 2020-10-05 07:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_auto_20201005_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='score',
        ),
        migrations.AddField(
            model_name='report',
            name='json_report',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
