# Generated by Django 3.1.1 on 2020-10-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0011_auto_20201005_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
        migrations.AddField(
            model_name='server',
            name='shared_with',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='auth.user'),
            preserve_default=False,
        ),
    ]
